name: Manual Build App Image From Template (Release)
run-name: Manual Build App Image for "${{ github.event.repository.name }}"

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: "Tag version to build image for"
        required: false
jobs:
  build-image:
    uses: supervisely-ecosystem/workflows/.github/workflows/build_image_from_template.yml@master
    with:
      image_name: "${{ github.event.repository.name }}"
      tag_version: "${{ github.event.inputs.tag_version }}"
      config_file: "supervisely/config.json"
      runtime_base_image: "base-py-cuda-hardened"
      cve_checks: true
