name: Docker Image Build

on: 
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Docker Image Tag (without "v")'     
        required: true
        type: string
jobs:
  build-image:
    uses: supervisely-ecosystem/workflows/.github/workflows/build_image_from_template.yml@master
    with:
      tag_version: ${{ inputs.tag_version }}
      config_file: "supervisely/config.json"
      image_name: "ritm"
      tag_ref_name: "6.73.567"
      runtime_base_image: "base-py-cuda-hardened"
      cve_checks: true
      no_cache_requirements: true
